#!/bin/bash

export VERSION="v0.0.1"
export IOTSTACKPWD="${IOTSTACK_IOTSTACKPWD:-$(pwd)}"
export HOSTUSER="${IOTSTACK_HOSTUSER:-$(whoami)}"
export HOSTSSH_ADDR="${IOTSTACK_HOSTSSH_ADDR:-"host.docker.internal"}"
export HOSTSSH_PORT="${IOTSTACK_HOSTSSH_PORT:-22}"
export HOST_CON_IP="${IOTSTACK_HOST_CON_IP:-"localhost"}"
export API_PORT="${IOTSTACK_API_PORT:-32128}"
export WUI_PORT="${IOTSTACK_WUI_PORT:-32777}"
export API_INTERFACE="${IOTSTACK_API_INTERFACE:-0.0.0.0}"
export PYCLI_CON_API="${IOTSTACK_PYCLI_CON_API:-"$HOSTSSH_ADDR:$API_PORT"}"
export PYCLI_CON_WUI="${IOTSTACK_PYCLI_CON_WUI:-"$HOST_CON_IP:$WUI_PORT"}"
